# remark:基本脚手架 author:lianghb date:2019-05-21
spring:
  datasource:
    url: jdbc:mysql://cdb-6k60thc5.gz.tencentcdb.com:10049/hqplus?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jane0513
    type: com.alibaba.druid.pool.DruidDataSource
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    database: 0
    host: 134.175.140.200
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 20
        min-idle: 1
        max-idle: 8
        max-wait: 1000
  rabbitmq:
    host: 134.175.140.200
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10