# remark:基本脚手架 author:lianghb date:2019-05-21
spring:
  datasource:
    url: jdbc:mysql://172.16.1.73:3306/hqplus?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: GPDI@hqplus.510630
    type: com.alibaba.druid.pool.DruidDataSource
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    database: 0
    host: 172.16.1.73
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 20
        min-idle: 1
        max-idle: 8
        max-wait: 1000
  rabbitmq:
    host: 172.16.1.73
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10

eureka:
  instance:
    prefer-ip-address: true
  server:
    # 开启eureka自我保护机制
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://172.16.1.76:8761/eureka

#微信支付配置
#mxhid 商户号
#秘钥key
#notify_url 回调接口
wxpay:
  appid: wxe4a9af4db320ef7a
  mchid: 1484266082
  key: 48A010DDF97A01F6D6826CF40E6EDECC
  notify_url: http://192.168.1.209:9009/v1/app/payment/wxpay/notify



#支付宝支付配置
alipay:
  #支付同步返回地址
  aliReturnUrl: xxxxx
  #支付异步通知地址
  aliNotifyUrl: xxxxx
  #  #产品码
  productNo: QUICK_MSECURITY_PAY
  #超时时间
  timeExpress: 15m
  #支付网关
  url: https://openapi.alipaydev.com/gateway.do
  #商户号
  appid: 2016091500519530
  #私钥
  privateKey:
  #公钥
  aliPublicKey:
  #加密方式
  signType: RSA2
  format: JSON
  charset: UTF-8

#ios 推送
#推送的key
push:
  appKey: 1d1a3e7b4b5b987c6abbf249
  masterSecret: 7ad3968dcea5e51c0123eaa8